name: 'Prepare Changelog'
on:
  push:
    branches:
      - main
env:
  branch: "sync-changelog"
  title: "[Release Prep]: Update proposed changelog"
  commit: "pre-release :: add changesets"
  body: |
    Automated and continuously updated PR for adding changeset entries for merged PRs.

    TODO
    - [ ] Determine patch/minor/major impact for each package for each changeset
    - [ ] if applicable, mark/remove certain changes as omitted from the changelog
    - [ ] if applicable, bundle changes together in to a single "change set"


jobs:
  determine-changes:
    name: Determine Changes
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v2.0.0
      - run: pnpx changeset-recover@latest --non-interactive
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.commit }}
          draft: true
          branch: ${{ env.branch }}
          base: 'main'
          title: ${{ env.title }}
          body: ${{ env.body }}
