# For every push to the master branch, this publishes an NPM package to the
# "unstable" NPM tag.

name: Publish Unstable

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: publish-unstable-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: "NPM Publish"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          # This creates an .npmrc that reads the NODE_AUTH_TOKEN environment variable
          registry-url: 'https://registry.npmjs.org'

      - name: set versions
        run: node ./test-packages/unstable-release/version.js

      - name: npm publish
        run: node ./test-packages/unstable-release/publish.js
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
